### ISSUE TITLE
Organize testing of PRs against git-annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/git-annex#14]
so we could test perspective patches etc

**Comment by jwodder** [comment]
Done.  (I pushed the changes directly to master instead of creating a PR because the workflow needs to be on master in order to run & test.)  I have created [this workflow](https://github.com/datalad/git-annex/blob/master/.github/workflows/build-prs.yml) and [script](https://github.com/datalad/git-annex/blob/master/.github/workflows/tools/prdispatch.py) that is scheduled to run every 5 minutes (though so far it's been every 7 to 31 minutes) and queries for open, mergeable PRs against `upstream/master` that have had certain activity (PR created, commit pushed, PR head force-pushed, or PR base branch changed) occur since the script successfully ran last.  It then triggers builds of the merged PR on all three OSes.  The script has already triggered [these](https://github.com/datalad/git-annex/actions/runs/374783240) [three](https://github.com/datalad/git-annex/actions/runs/374783205) [runs](https://github.com/datalad/git-annex/actions/runs/374783216) for [this PR](https://github.com/datalad/git-annex/pull/16).
