### ISSUE TITLE
Builds failing on Ubuntu due to lack of singularity-container

### ISSUE THREAD

**Issue by jwodder** [datalad/git-annex#146]
The Ubuntu builds run on `ubuntu-latest`, which was recently upgraded from 20.04 to 22.04.  Unfortunately, the neurodebian archive for the latter does not have a `singularity-container` package, and so the builds are now failing.

**Comment by yarikoptic** [comment]
yeap, aware of it and do not have solution from neurodebian yet.  Please either 

- resort to installing singularity using recommended procedure from singularity project, or
- revert to 20.04 if that remains an option

**Comment by jwodder** [comment]
@yarikoptic Is a specific version of Singularity required?  The latest version of Singularity 2.x doesn't compile due to a bug in automake, so I'm wondering if Singularity 3 is acceptable.

**Comment by yarikoptic** [comment]
it should work just fine with contemporary 3.x series.  

Note: I kept 2.x in NeuroDebian since it was the one, C (not Go), I could build without issues across all distributions. With 3.x, most of golang libraries aren't backported and there were other dependencies issues IIRC preventing to just reuse the same build across distributions, but I might look back into it for more recent ubuntus etc at some point.
