### ISSUE TITLE
workflows do not work in a fork

### ISSUE THREAD

**Issue by joeyh** [datalad/git-annex#86]
I forked this repo intending to use the windows build workflow, with the goal of building with profiling enabled. But that workflow hardcodes datalad/git-annex when downloading libmagic, which fails with an access denied error, so it needs to be edited in order to work in a fork.

It would be nice if this workflow worked unmodified in a fork. Perhaps that hard coding could be avoided, although I don't know how. After deleting the libmagic stanzas from the workflow, it seems to mostly work, at least through building git-annex.

**Comment by yarikoptic** [comment]
I guess we should just use `GITHUB_REPOSITORY` (https://docs.github.com/en/actions/learn-github-actions/environment-variables) env var to avoid hardcoding `datalad/git-annex` but I have not analyzed on what other ramifications would be as what else needs to be tuned up etc.

@joeyh should we may be enable a build here with profiling enabled or is that a rare need (I guess you need it only for windows?)?

**Comment by jwodder** [comment]
@joeyh I assume you're referring to [this step](https://github.com/datalad/git-annex/blob/7052974a49150948ddd82f9314b92f51aa6bad62/.github/workflows/build-windows.yaml#L91-L98)?  The problem isn't that it "hardcodes datalad/git-annex"; the problem is that it downloads a build artifact from a GitHub Action, which requires a GitHub token with admin(?) permission for the datalad/file-windows repository.

@yarikoptic One way around this would be to create a GitHub release of datalad/file-windows and upload a recent build artifact as a release asset (which can be done once manually, as it's unlikely the artifact will change much going forwards) and have the build step download that release asset.

**Comment by yarikoptic** [comment]
> @yarikoptic One way around this would be to create a GitHub release of datalad/file-windows and upload a recent build artifact as a release asset (which can be done once manually, as it's unlikely the artifact will change much going forwards) and have the build step download that release asset.

Sounds good.  Please create a release -- we seems only inherited a tag from the original repo we "forked" and never created our own releases there.  Indeed, probably not worth automating since we aren't rebuilding it on a regular basis

**Comment by jwodder** [comment]
@yarikoptic [Release created](https://github.com/datalad/file-windows/releases/tag/2019.09.28).
